### ISSUE TITLE
Received linker warning LNK4221

### ISSUE THREAD

**Issue by mwpowellhtx** [commontk/qt-easy-build#14]
I received numerous linker warnings:

`warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library`

Do not know if this is normal.

**Comment by jcfr** [comment]
Thanks for your report. 

> Do not know if this is normal.

Since these are warnings specific to Qt, I am closing the issue.

I suggest you ignore these.

Ideally, these warnings should be addressed upstream in the Qt project itself.

Considering qt accepts only critical patches for 4.8.x maintenance branch, if the warnings are also reported when building Qt5, it may make sense to report upstream.
